### ISSUE TITLE
Add support for wedgies

### ISSUE THREAD

**Issue by frostburn** [Sin-tel/temper#8]
You can hide them by default if wedgies take up too much space, but it would be nice to see a canonical form that doesn't depend on aesthetic choices for the basis.

Bonus points if you can search by wedgie too.

**Comment by Sin-tel** [comment]
I don't think the added complexity of importing a bunch of exterior algebra is worth the payoff here. Plucker coordinates aren't that hard to implement but I don't think they should be shown to users, nor do they provide any computational benefit.
